services:
  - type: web
    name: video-segmenter-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    preDeploy: "apt-get update && apt-get install -y ffmpeg"